[data_paths]
aotizpath = 'aqinsc/aotizhongxin-c.csv'
changpath = 'aqinsc/changping-c.csv'
dingpath = 'aqinsc/dingling-c.csv'
dongpath = 'aqinsc/dongsi-c.csv'
guapath = 'aqinsc/guanyuan-c.csv'
gucpath = 'aqinsc/gucheng-c.csv'
huapath = 'aqinsc/huairo-c.csv'
nonpath = 'aqinsc/nonzhanguan-c.csv'
shunpath = 'aqinsc/shunyi-c.csv'
tiapath = 'aqinsc/tiantan-c.csv'
walpath = 'aqinsc/wanliu-c.csv'
waxpath = 'aqinsc/wanshouxigong-c.csv'
